image: gcc

build-and-test:
  stage: build
  before_script:
    - pwd
    - source `find .. -name section_helper.sh`

    - start_section install_linux_packages "Installing missing Linux packages"
    - apt update && apt -y install cmake librocksdb-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev libomp-dev
    - end_section install_linux_packages

  script:
    - start_section install_collocatordb "Building and installing collocatordb"
    - mkdir -p build
    - cd build
    - cmake ..
    - make
    - make install
    - ldconfig
    - ctest --extra-verbose
    - strip --strip-unneeded `find -name libcollocatordb.so`
    - cd ..
    - end_section install_collocatordb

  artifacts:
    paths:
      - "build/libcollocatordb.so*"
      - "build/libcollocatordb*.a"
